# Generated by Django 5.2.1 on 2025-05-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='Your_note',
            new_name='your_note',
        ),
    ]
