# Generated by Django 5.2.1 on 2025-05-14 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_your_note_profession_your_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publication', models.ManyToManyField(to='myapp.publication')),
                ('awards', models.ManyToManyField(to='myapp.awards')),
                ('certificate', models.ManyToManyField(to='myapp.certification')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profession')),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profileimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emergencycontact')),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profileimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
