# Generated by Django 5.2.1 on 2025-05-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mainprofile_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='Publication',
            field=models.ManyToManyField(blank=True, null=True, related_name='publication', to='myapp.publication'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, related_name='awards', to='myapp.awards'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, null=True, related_name='certificate', to='myapp.certification'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profession'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profileimage'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profileimage'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
