# Generated by Django 5.2.1 on 2025-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_awards_user_certification_user_emergencycontact_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='Publication',
            field=models.ManyToManyField(blank=True, related_name='publication', to='myapp.publication'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='awards', to='myapp.awards'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='myapp.certification'),
        ),
    ]
