# Generated by Django 5.2.1 on 2025-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_mainprofile_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='certification', to='myapp.certification'),
        ),
    ]
