# Generated by Django 5.2.1 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_awards_user_alter_certification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
