# Generated by Django 5.2.1 on 2025-05-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_mainprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_varified',
            new_name='is_varified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='otp_varified',
            new_name='is_varified',
        ),
    ]
