# Generated by Django 5.2.1 on 2025-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
