# Generated by Django 5.2.1 on 2025-05-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_certification_certificate_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprofile',
            name='working_hours',
            field=models.ManyToManyField(blank=True, related_name='main_working_hours', to='myapp.workinghours'),
        ),
    ]
