# Generated by Django 5.2.1 on 2025-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_question_option_patientassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassessment',
            name='text_amswer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
