# Generated by Django 5.2.1 on 2025-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_patientassessment_text_amswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassessment',
            name='select_sub_option',
            field=models.ManyToManyField(related_name='assessment_sub_option', to='myapp.option'),
        ),
    ]
