# Generated by Django 5.2.1 on 2025-05-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_patientassessment_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassessmentans',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='myapp.patientassessment'),
        ),
    ]
