# Generated by Django 5.2.1 on 2025-05-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_weboption_webquestion_webpatientassessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpatientassessmentans',
            name='select_option',
        ),
        migrations.RemoveField(
            model_name='webpatientassessment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webpatientassessmentans',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='webpatientassessmentans',
            name='question',
        ),
        migrations.DeleteModel(
            name='WebOption',
        ),
        migrations.DeleteModel(
            name='WebPatientAssessment',
        ),
        migrations.DeleteModel(
            name='WebPatientAssessmentAns',
        ),
        migrations.DeleteModel(
            name='WebQuestion',
        ),
    ]
