# Generated by Django 5.2.1 on 2025-05-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_webpatientassessmentans_select_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('multi_choice', 'Multiple Choice'), ('text', 'Free text input')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_patientassessment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebPatientAssessmentAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_answers', to='myapp.webpatientassessment')),
                ('select_option', models.ManyToManyField(related_name='assessment_option', to='myapp.weboption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='myapp.webquestion')),
            ],
        ),
        migrations.AddField(
            model_name='weboption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_options', to='myapp.webquestion'),
        ),
    ]
