# Generated by Django 5.2.1 on 2025-05-27 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_workinghours_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.CharField(blank=True, max_length=50, null=True)),
                ('test_name', models.CharField(blank=True, max_length=50, null=True)),
                ('results', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('positive +ve', 'Positive +ve'), ('negative -ve', 'Negative -ve'), ('borderline', 'Borderline'), ('detected', 'Detected')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.TextField()),
                ('appointment_type', models.CharField(choices=[('regular check_up', 'Regular Check_up'), ('urgent check_up', 'Urgent Check_up')], max_length=50)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_created_by', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'select_role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(blank=True, choices=[('compliants', 'Compliants'), ('history & symptoms', 'History & Symptoms'), ('physical examination', 'Physical Examination'), ('diagnosis', 'Diagnosis'), ('treatment plan', 'Treatment Plan'), ('recomended test', 'Recommended Test'), ('medication', 'Medication'), ('immediate attention required ', 'Immediate Attention Required')], max_length=50, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_patient', to='myapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_summery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.diagnosisdetail')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_history', to='myapp.labreport')),
            ],
        ),
    ]
