# Generated by Django 5.2.1 on 2025-05-29 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_category_labreport_appointment_diagnosisdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StaffDoctorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'select_role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'select_role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assigned_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
