# Generated by Django 5.2.1 on 2025-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_appointment_cancelled_at_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='receive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_issued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
