# Generated by Django 5.2.1 on 2025-05-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_awards_receive_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='user',
            new_name='doctor',
        ),
    ]
