# Generated by Django 5.2.1 on 2025-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_user_workinghours_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
