# Generated by Django 5.2.1 on 2025-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_workinghours_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
