# Generated by Django 5.2.1 on 2025-06-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_history_status_labreport_report_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('diagnosis_summery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.diagnosisdetail')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.labreport')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patienthistory')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
