# Generated by Django 5.2.1 on 2025-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_patienthistory_historyrelation_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('regular check_up', 'Regular Check_up'), ('urgent check_up', 'Urgent Check_up')], max_length=50, null=True),
        ),
    ]
