# Generated by Django 5.2.1 on 2025-06-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
