# Generated by Django 5.2.1 on 2025-06-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_user_experience_user_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosisdetail',
            old_name='patient',
            new_name='patient_name',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='lab_report',
            field=models.ManyToManyField(blank=True, related_name='lab_history', to='myapp.labreport'),
        ),
        migrations.AlterField(
            model_name='diagnosisdetail',
            name='diagnosis_type',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('history & symptoms', 'History & Symptoms'), ('physical examination', 'Physical Examination'), ('diagnosis', 'Diagnosis'), ('treatment plan', 'Treatment Plan'), ('recommended test', 'Recommended Test'), ('medication', 'Medication'), ('immediate attention required ', 'Immediate Attention Required')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_appointment', to='myapp.appointment'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='results',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('positive +ve', 'Positive +ve'), ('negative -ve', 'Negative -ve'), ('borderline', 'Borderline'), ('detected', 'Detected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='diagnosis_summery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_history', to='myapp.diagnosisdetail'),
        ),
        migrations.DeleteModel(
            name='HistoryRelation',
        ),
    ]
