# Generated by Django 5.2.1 on 2025-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_patient_name_diagnosisdetail_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='status',
            field=models.CharField(choices=[('recovered', 'Recovered'), ('pending', 'Pending'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=50),
        ),
    ]
