# Generated by Django 5.2.1 on 2025-06-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_patienthistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='diagnosis_summery',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='lab_report',
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment'),
        ),
    ]
