# Generated by Django 5.2.1 on 2025-06-12 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_patienthistory_diagnosis_summery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(choices=[('Medical Assistant', 'Medical Assistant'), ('Administrator', 'Administrator'), ('Lab Technician', 'Lab Technician'), ('Cleaner', 'Cleaner')], max_length=50)),
                ('duty', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'select_role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'select_role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assigned_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffDoctorRelation',
        ),
    ]
