# Generated by Django 5.2.1 on 2025-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_staffmanagement_delete_staffdoctorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmanagement',
            name='staff_role',
            field=models.CharField(choices=[('Medical Assistant', 'Medical Assistant'), ('Administrator', 'Administrator'), ('Lab Technician', 'Lab Technician'), ('Cleaner', 'Cleaner'), ('Ward Nurse', 'Ward Nurse')], max_length=50),
        ),
    ]
