# Generated by Django 5.2.1 on 2025-06-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_staffmanagement_end_time_staffmanagement_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentReminder',
        ),
    ]
