# Generated by Django 5.2.1 on 2025-06-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_delete_appointmentreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_appointment', to='myapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('medicine_status', models.CharField(blank=True, choices=[('Taken', 'Taken'), ('Pending', 'Pending'), ('Skipped', 'Skipped')], max_length=50, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_reminder', to='myapp.appointment')),
            ],
        ),
    ]
