# Generated by Django 5.2.1 on 2025-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_appointmentreminder_medicinereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='reasons_to_reschedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
