# Generated by Django 5.2.1 on 2025-06-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisdetail',
            name='appointment',
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='myapp.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosisdetail',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_detail', to='myapp.diagnosis'),
        ),
    ]
