# Generated by Django 5.2.1 on 2025-06-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_diagnosisdetail_appointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='myapp.appointment'),
        ),
    ]
