# Generated by Django 5.2.1 on 2025-06-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_alter_diagnosis_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='datetime',
        ),
    ]
