# Generated by Django 5.2.1 on 2025-06-25 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_remove_appointmentreminder_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
