# Generated by Django 5.2.1 on 2025-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_appointmentreminder_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreminder',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
